### PR TITLE
Encoder platforms

### PR DESCRIPTION
**Pull request by camnewnham**
This PR just adds actions builds for the encoder on all platforms. Relates to https://github.com/atteneder/DracoUnity/pull/48

Note that meta files will still need to be generated to include these in DracoUnity

### CODE REVIEW

**Comment by camnewnham** [comment]
Not sure why the tests are failing all of a sudden - note that the only changes here were to an (unrelated) action. Perhaps there's been a change to the VMs (these specify `windows-latest` etc..)

**Comment by atteneder** [comment]
Thanks for this contribution!

We have to get this working first though. Would you be able to look into why some builds are failing? I've seen you've also changed some compiler versions, which might cause errors as well.

**Comment by camnewnham** [comment]
> I've seen you've also changed some compiler versions, which might cause errors as well.

The only changes I've made were to `unity.yml` file - the failing component is from `test.yml` I thought would be independent... Or am I missing something here?

The last time the tests were run for this repo [was 12 months ago](https://github.com/atteneder/draco/actions/workflows/unity.yml)

**Comment by atteneder** [comment]
@camnewnham You're right, I wasn't aware of `test.yml`, since it is from the original Google repository. It worked [4 months ago](https://github.com/atteneder/draco/actions/workflows/test.yml) and is broken now. Likely nothing this PR caused. I'll have to look into it.

**Comment by atteneder** [comment]
@camnewnham Again, thanks for the contribution!

I've rebased the whole project onto Google's Draco 1.5.5 and did some other build fixes, causing a conflict now.

Then I manually rebased your work.

I'll still have to look on the build size impacts and decide whether to include all of them by default, but at  least people can download/build the required libs now easily.

**Pull request closed without merging**
