### PR TITLE
Include  x86_64 plugin in build workflow

### PR DESCRIPTION
**Pull request by kbabilinski**
Updated the unity.yml file to include the x86_64 version of the draco plugin

### CODE REVIEW

**Comment by atteneder** [comment]
@Babilinski Thanks for the PR!

Previously I did not add that ABI in order to save resources (like GIT LFS traffic).
What's your use for it? I'd assume support for Chrome OS, right?

**Comment by kbabilinski** [comment]
It's actually I created the PR for developers that are using Magic Leap 2, but it should work for Chrome OS as well.

I can resolve the merge conflicts if you have a minute to take a look at the PR. It can be tested in Android Studio by creating a virtual device that targets Android 10, x86_64.

Thank you for all of your open source contributions 🙏

**Comment by Babilinski** [comment]
I will reserve the merge conflicts if you have a minute to take a look at it.

Thank you for all of your open source contributions 🙏

**Comment by atteneder** [comment]
Thanks for the insight, that's good to know.

Don't worry about rebasing it. I already added it in an internal mirror. Expect this to land soon.

**Pull request closed without merging**
